wandb_version: 1

learning_rate:
  desc: null
  value: 2.0e-05
weight_decay:
  desc: null
  value: 0.01
num_train_epochs:
  desc: null
  value: 10
train_subsample_size:
  desc: null
  value: 1000
architecture:
  desc: null
  value: distilbert
dataset_name:
  desc: null
  value: rotten_tomatoes
model_name:
  desc: null
  value: distilbert-base-uncased
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705498841.995252
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 15
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 15
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.15.12
      6: 4.31.0
      8:
      - 1
      - 5
      13: linux-x86_64
